version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"

  php:
    build:
      context: .  # Use the directory with the Dockerfile
    container_name: php_container
    ports:
      - "8081:80"  # Change the port here (PHP will now be accessible on port 8081)
    volumes:
      - ./src:/var/www/html
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

